import type { INodeProperties } from 'n8n-workflow';

export const payrollAdministrationReportsDescription: INodeProperties[] = [
                {
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					]
				}
			},
			"options": [
				{
					"name": "Get Accumulated Basic Journal Results Report By Payroll Administration ID",
					"value": "Get Accumulated Basic Journal Results Report By Payroll Administration ID",
					"action": "Download accumulated basic journal results report",
					"description": "__Activity name :__ GetAccumulatedBasicJournalResultsReportByPayrollAdministrationId\n\nAcquire accumulated basic journal results reports (cumulatief journaal niet-verdicht en verdicht) at the payroll administration level. Currently this endpoint supports following report types to be requested:\n_Please note: this endpoint may only be used to acquire a report in the pdf-type format_ \n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/accumulatedbasicjournalresultsreport"
						}
					}
				},
				{
					"name": "Get Accumulations And Balances Report By Payroll Administration ID",
					"value": "Get Accumulations And Balances Report By Payroll Administration ID",
					"action": "Download accumulations and balances reports",
					"description": "__Activity name :__ GetAccumulationsAndBalancesReportByPayrollAdministrationId\n\nAcquire the reports for either accumulations or balances at the payroll administration level. Currently this endpoint supports following report types to be requested:\n* baseForCalculationBalancesAtStartOfYear (grondslag begin jaar)\n\n* leaveBalancesAtStartOfYear (verlof begin jaar)\n\n* leaveAccrualWithinYear (opbouw verlof ulsa)\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/accumulationsandbalancesreport"
						}
					}
				},
				{
					"name": "Get Annual Payroll Tax Return Report By Payroll Administration ID",
					"value": "Get Annual Payroll Tax Return Report By Payroll Administration ID",
					"action": "Download annual payroll tax return report",
					"description": "__Activity name :__ GetAnnualPayrollTaxReturnReportByPayrollAdministrationId\n\nAcquire the annual payroll tax return report (jaaroverzicht loongaangiftestaat) on payroll administration level, as generated by the reporting service.\n\n_Please note: this endpoint may only be used to acquire a report in the pdf-type format_ \n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/annualpayrolltaxreturnreport"
						}
					}
				},
				{
					"name": "Get Annual Wagesheet Report By Payroll Administration ID",
					"value": "Get Annual Wagesheet Report By Payroll Administration ID",
					"action": "Download annual wage sheet report",
					"description": "__Activity name :__ GetAnnualWagesheetReportByPayrollAdministrationId\n\nAcquire the annual wage sheet report (verzamelloonstaat) on payroll administration level, as generated by the reporting service.\n\n__Note: __ For the querystring parameters take note of the following logic either reportYear has a value or start and endperiod have a value\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/annualwagesheetreport"
						}
					}
				},
				{
					"name": "Get Attachments Of Earnings Report By Payroll Administration ID",
					"value": "Get Attachments Of Earnings Report By Payroll Administration ID",
					"action": "Download attachment of earnings report",
					"description": "__Activity name :__ GetAttachmentsOfEarningsReportByPayrollAdministrationId\n\nDownload the attachment of earnings report for the administration\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/attachmentsofearningsreport"
						}
					}
				},
				{
					"name": "Get Deviating Premiums Wab Report By Payroll Administration ID",
					"value": "Get Deviating Premiums Wab Report By Payroll Administration ID",
					"action": "Download WAB deviations report",
					"description": "__Activity name :__ GetDeviatingPremiumsWabReportByPayrollAdministrationId\n\nThe percentage deviation between the contract hours and the actual standard hours to assess whether the low wab premium should be revised to the high wab premium.\n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/deviatingpremiumswab"
						}
					}
				},
				{
					"name": "Get Payroll Administration Settings Report By Payroll Administration ID",
					"value": "Get Payroll Administration Settings Report By Payroll Administration ID",
					"action": "Download payroll administration configuration report",
					"description": "__Activity name :__ GetPayrollAdministrationSettingsReportByPayrollAdministrationId\n\nAcquire the payroll administration configuration report (overzicht inrichting salarisverwerking) on payroll administration level for a year, as generated by the reporting service.\n\n_Please note: this endpoint may only be used to acquire a report in the pdf-type format_ \n",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/providers/employers/payrolladministrations/{{$parameter[\"payrollAdministrationId\"]}}/payrolladministrationsettingsreport"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/accumulatedbasicjournalresultsreport",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/pdf",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Type",
			"name": "reportType",
			"required": true,
			"description": "The type of report that is requested.",
			"default": "nonAggregated",
			"type": "options",
			"options": [
				{
					"name": "Non Aggregated",
					"value": "nonAggregated"
				},
				{
					"name": "Aggregated Per General Ledger Account",
					"value": "aggregatedPerGeneralLedgerAccount"
				}
			],
			"routing": {
				"send": {
					"type": "query",
					"property": "reportType",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Grouping Type",
			"name": "groupingType",
			"required": true,
			"description": "The type of grouping that is requested. This affects the way the data is presented within the given report.",
			"default": "perPeriod",
			"type": "options",
			"options": [
				{
					"name": "Per Period",
					"value": "perPeriod"
				},
				{
					"name": "Per Distribution Unit",
					"value": "perDistributionUnit"
				},
				{
					"name": "Per Period Per Distribution Unit",
					"value": "perPeriodPerDistributionUnit"
				}
			],
			"routing": {
				"send": {
					"type": "query",
					"property": "groupingType",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Start Period",
			"name": "startPeriod",
			"required": true,
			"description": "First period (=from) of the requested timebox. Use the format 'YYYYPP'",
			"default": 201901,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "startPeriod",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "End Period",
			"name": "endPeriod",
			"required": true,
			"description": "Last period (=up to and including) of the requested timebox. Use the following 'YYYYPP'",
			"default": 201912,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "endPeriod",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulated Basic Journal Results Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/accumulationsandbalancesreport",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/pdf",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Type",
			"name": "reportType",
			"required": true,
			"description": "The type of report that is requested.",
			"default": "baseForCalculationBalancesAtStartOfYear",
			"type": "options",
			"options": [
				{
					"name": "Base For Calculation Balances At Start Of Year",
					"value": "baseForCalculationBalancesAtStartOfYear"
				},
				{
					"name": "Leave Balances At Start Of Year",
					"value": "leaveBalancesAtStartOfYear"
				},
				{
					"name": "Leave Accrual Within Year",
					"value": "leaveAccrualWithinYear"
				}
			],
			"routing": {
				"send": {
					"type": "query",
					"property": "reportType",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Year",
			"name": "reportYear",
			"required": true,
			"description": "A valid year for which the information is requested.",
			"default": "2023",
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "reportYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Include Employments That Ended Before Start Of The Year",
			"name": "includeEmploymentsThatEndedBeforeStartOfTheYear",
			"description": "If set to true employments with an enddate before the start of the reportYear will be included in the output.",
			"default": false,
			"type": "boolean",
			"routing": {
				"send": {
					"type": "query",
					"property": "includeEmploymentsThatEndedBeforeStartOfTheYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Accumulations And Balances Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/annualpayrolltaxreturnreport",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Payroll Tax Return Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Payroll Tax Return Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/json;version=2018-01-01",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Payroll Tax Return Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Payroll Tax Return Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Year",
			"name": "reportYear",
			"required": true,
			"description": "A valid year for which the information is requested.",
			"default": "2023",
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "reportYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Payroll Tax Return Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/annualwagesheetreport",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/pdf",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Year",
			"name": "reportYear",
			"description": "A valid year for which the information is requested.",
			"default": "2023",
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "reportYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Start Period",
			"name": "startPeriod",
			"description": "First period (=from) of the requested timebox. Use the format 'YYYYPP'",
			"default": 201901,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "startPeriod",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "End Period",
			"name": "endPeriod",
			"description": "Last period (=up to and including) of the requested timebox. Use the following 'YYYYPP'",
			"default": 201912,
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "endPeriod",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Annual Wagesheet Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/attachmentsofearningsreport",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Attachments Of Earnings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Attachments Of Earnings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/pdf",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Attachments Of Earnings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Attachments Of Earnings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Year",
			"name": "reportYear",
			"required": true,
			"description": "A valid year for which the information is requested.",
			"default": "2023",
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "reportYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Attachments Of Earnings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/deviatingpremiumswab",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Deviating Premiums Wab Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Deviating Premiums Wab Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/pdf",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Deviating Premiums Wab Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Deviating Premiums Wab Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Year",
			"name": "reportYear",
			"required": true,
			"description": "A valid year for which the information is requested.",
			"default": "2023",
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "reportYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Deviating Premiums Wab Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "GET /providers/employers/payrolladministrations/{payrollAdministrationId}/payrolladministrationsettingsreport",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Payroll Administration Settings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Authorization",
			"name": "Authorization",
			"required": true,
			"description": "A valid Bearer token for authorizing the request.",
			"default": "Bearer <TOKEN>",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Authorization": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Payroll Administration Settings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Accept",
			"name": "Accept",
			"required": true,
			"description": "The accept header is used to influence what type of output is returned and in most cases the version of the output",
			"default": "application/json;version=2018-01-01",
			"type": "string",
			"routing": {
				"request": {
					"headers": {
						"Accept": "={{ $value }}"
					}
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Payroll Administration Settings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Payroll Administration ID",
			"name": "payrollAdministrationId",
			"required": true,
			"description": "The unique identifier of an administration",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Payroll Administration Settings Report By Payroll Administration ID"
					]
				}
			}
		},
		{
			"displayName": "Report Year",
			"name": "reportYear",
			"required": true,
			"description": "A valid year for which the information is requested.",
			"default": "2023",
			"type": "number",
			"routing": {
				"send": {
					"type": "query",
					"property": "reportYear",
					"value": "={{ $value }}",
					"propertyInDotNotation": false
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Payroll Administration Reports"
					],
					"operation": [
						"Get Payroll Administration Settings Report By Payroll Administration ID"
					]
				}
			}
		},
];
